# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'lynxTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lynxTestProject
  pod 'RxSwift'
  pod 'RxRelay'
  pod 'RxCocoa'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'RxFirebase/Firestore'
  pod 'RxFirebase/RemoteConfig'
  pod 'RxFirebase/Database'
  pod 'RxFirebase/Storage'
  pod 'RxFirebase/Auth'
  pod 'RxFirebase/Functions'
end
