# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'lynxTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lynxTestProject
  pod 'RxSwift'
  pod 'RxRelay'
  pod 'RxCocoa'
  pod 'Firebase/Analytics'
end
